---
title: "README.Rmd"
author: "brittneynelsen"
date: "2021-03-25"
output: github_document
---

>Abstract

Over the years koala populations have been decreasing, this led them to be listed as a threatened species. Due to the recent brush fires that happened in Australia in 2020, news articles have stated that koalas could be facing extinction in New South Wales Australia by the year 2050. But the questions are, how much have the koala species declined over the past five years? Is there a change of location? and what are the reasons on why the koalas left the original location. I will be using data called Rinat to help me answer these questions. I plan on using this data to show how much the population has decreased. I will also use this data locate where koala populations have occurred on a map and to see if there was a change in location due to factors affecting the koala population. I plan to use exploratory data analysis to search for my answers by visualizing, transforming, and modeling the data. My hypothesis is that there will be a change of location due to factors such as brush fires. This will help me understand why they left that location and how I can help raise awareness to slow the decline of koala populations.

>Introduction


>Methods

1. I installed rinat package using remotes function
2. I installed tidyverse
3. I installed rinat
4. I retrieved the koala information
5. I read koala information using their scientific name
6. I retrieved koala data specifically from 2015 Queensland Australia data
7. I mapped koala data location from 2015

>Results


>Discussion


>Literature Cited

I used R version 4.0.3 (2020-10-10)

RStudio Team (2020). RStudio: Integrated Development Environment for R. RStudio, PBC,
  Boston, MA URL http://www.rstudio.com/.

Vijay Barve and Edmund Hart (2021). rinat: Access 'iNaturalist' Data Through APIs.
  https://docs.ropensci.org/rinat/ (website) https://github.com/ropensci/rinat (devel).

H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York,
  2016.

